debug: true
server:
  port: 8089
  servlet:
    context-path: /
     
spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/java_take_attendance_student
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         facebook:
          clientId: 802729353941880
          clientSecret: 3ad595734d98bb8c08848c9c9dbd350f
          scope:
           - email
           - public_profile     
